# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmIdSizingGuiVp1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GmIdMainWindow(object):
    def setupUi(self, GmIdMainWindow):
        GmIdMainWindow.setObjectName("GmIdMainWindow")
        GmIdMainWindow.resize(1162, 923)
        self.centralwidget = QtWidgets.QWidget(GmIdMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.titleToolBox = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titleToolBox.setFont(font)
        self.titleToolBox.setAlignment(QtCore.Qt.AlignCenter)
        self.titleToolBox.setObjectName("titleToolBox")
        self.horizontalLayout_6.addWidget(self.titleToolBox)
        self.labelDevType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelDevType.setFont(font)
        self.labelDevType.setText("")
        self.labelDevType.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDevType.setObjectName("labelDevType")
        self.horizontalLayout_6.addWidget(self.labelDevType)
        self.horizontalLayout_6.setStretch(0, 11)
        self.horizontalLayout_6.setStretch(1, 8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayoutMain = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMain.setObjectName("horizontalLayoutMain")
        self.verticalLayoutPlot = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlot.setObjectName("verticalLayoutPlot")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.titlePlotCorner = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titlePlotCorner.setFont(font)
        self.titlePlotCorner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titlePlotCorner.setObjectName("titlePlotCorner")
        self.horizontalLayout_51.addWidget(self.titlePlotCorner)
        self.comboBoxDesignCorner = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDesignCorner.sizePolicy().hasHeightForWidth())
        self.comboBoxDesignCorner.setSizePolicy(sizePolicy)
        self.comboBoxDesignCorner.setObjectName("comboBoxDesignCorner")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.horizontalLayout_51.addWidget(self.comboBoxDesignCorner)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem)
        self.pushButtonPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.horizontalLayout_51.addWidget(self.pushButtonPlot)
        self.horizontalLayout_51.setStretch(0, 1)
        self.horizontalLayout_51.setStretch(1, 1)
        self.horizontalLayout_51.setStretch(2, 3)
        self.horizontalLayout_51.setStretch(3, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBoxCornerTT = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerTT.setStyleSheet("*{\n"
"background-color:rgb(119, 172, 48);\n"
"}")
        self.checkBoxCornerTT.setObjectName("checkBoxCornerTT")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerTT)
        self.checkBoxCornerFF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerFF.setStyleSheet("*{\n"
"background-color:rgb(0, 114, 189);\n"
"}")
        self.checkBoxCornerFF.setObjectName("checkBoxCornerFF")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerFF)
        self.checkBoxCornerSS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerSS.setStyleSheet("*{\n"
"background-color:rgb(126, 47, 142);\n"
"}")
        self.checkBoxCornerSS.setObjectName("checkBoxCornerSS")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerSS)
        self.checkBoxCornerFS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerFS.setStyleSheet("*{\n"
"background-color:rgb(217, 83, 25);\n"
"}")
        self.checkBoxCornerFS.setObjectName("checkBoxCornerFS")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerFS)
        self.checkBoxCornerSF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerSF.setStyleSheet("*{\n"
"background-color:rgb(237,177,32);\n"
"}")
        self.checkBoxCornerSF.setObjectName("checkBoxCornerSF")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerSF)
        self.checkBoxRef = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRef.setStyleSheet("*{\n"
"background-color:rgb(77,190,238);\n"
"}")
        self.checkBoxRef.setObjectName("checkBoxRef")
        self.horizontalLayout_21.addWidget(self.checkBoxRef)
        self.horizontalLayout_21.setStretch(0, 2)
        self.horizontalLayout_21.setStretch(1, 2)
        self.horizontalLayout_21.setStretch(2, 2)
        self.horizontalLayout_21.setStretch(3, 2)
        self.horizontalLayout_21.setStretch(4, 2)
        self.horizontalLayout_21.setStretch(5, 2)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_21)
        self.tabWidgetPlots = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetPlots.setObjectName("tabWidgetPlots")
        self.tabVstar = QtWidgets.QWidget()
        self.tabVstar.setObjectName("tabVstar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabVstar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        spacerItem1 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem1)
        self.topLPlotVstar = PlotWidget(self.tabVstar)
        self.topLPlotVstar.setObjectName("topLPlotVstar")
        self.horizontalLayout_49.addWidget(self.topLPlotVstar)
        spacerItem2 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem2)
        self.topRPlotVstar = PlotWidget(self.tabVstar)
        self.topRPlotVstar.setObjectName("topRPlotVstar")
        self.horizontalLayout_49.addWidget(self.topRPlotVstar)
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem3)
        self.horizontalLayout_49.setStretch(1, 1)
        self.horizontalLayout_49.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem4)
        self.botLPlotVstar = PlotWidget(self.tabVstar)
        self.botLPlotVstar.setObjectName("botLPlotVstar")
        self.horizontalLayout_50.addWidget(self.botLPlotVstar)
        spacerItem5 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem5)
        self.botRPlotVstar = PlotWidget(self.tabVstar)
        self.botRPlotVstar.setObjectName("botRPlotVstar")
        self.horizontalLayout_50.addWidget(self.botRPlotVstar)
        spacerItem6 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem6)
        self.horizontalLayout_50.setStretch(1, 1)
        self.horizontalLayout_50.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_50)
        self.verticalLayout_8.setStretch(0, 10)
        self.verticalLayout_8.setStretch(1, 10)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabVstar, "")
        self.tabId = QtWidgets.QWidget()
        self.tabId.setObjectName("tabId")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabId)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        spacerItem7 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem7)
        self.topLPlotId = PlotWidget(self.tabId)
        self.topLPlotId.setObjectName("topLPlotId")
        self.horizontalLayout_55.addWidget(self.topLPlotId)
        spacerItem8 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem8)
        self.topRPlotId = PlotWidget(self.tabId)
        self.topRPlotId.setObjectName("topRPlotId")
        self.horizontalLayout_55.addWidget(self.topRPlotId)
        spacerItem9 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem9)
        self.horizontalLayout_55.setStretch(1, 1)
        self.horizontalLayout_55.setStretch(3, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem10 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem10)
        self.botLPlotId = PlotWidget(self.tabId)
        self.botLPlotId.setObjectName("botLPlotId")
        self.horizontalLayout_57.addWidget(self.botLPlotId)
        spacerItem11 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem11)
        self.botRPlotId = PlotWidget(self.tabId)
        self.botRPlotId.setObjectName("botRPlotId")
        self.horizontalLayout_57.addWidget(self.botRPlotId)
        spacerItem12 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem12)
        self.horizontalLayout_57.setStretch(1, 1)
        self.horizontalLayout_57.setStretch(3, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_57)
        self.verticalLayout_11.setStretch(0, 10)
        self.verticalLayout_11.setStretch(1, 10)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabId, "")
        self.tabVgs = QtWidgets.QWidget()
        self.tabVgs.setObjectName("tabVgs")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tabVgs)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        spacerItem13 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem13)
        self.topLPlotVgs = PlotWidget(self.tabVgs)
        self.topLPlotVgs.setObjectName("topLPlotVgs")
        self.horizontalLayout_65.addWidget(self.topLPlotVgs)
        spacerItem14 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem14)
        self.topRPlotVgs = PlotWidget(self.tabVgs)
        self.topRPlotVgs.setObjectName("topRPlotVgs")
        self.horizontalLayout_65.addWidget(self.topRPlotVgs)
        spacerItem15 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem15)
        self.horizontalLayout_65.setStretch(1, 1)
        self.horizontalLayout_65.setStretch(3, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        spacerItem16 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem16)
        self.botLPlotVgs = PlotWidget(self.tabVgs)
        self.botLPlotVgs.setObjectName("botLPlotVgs")
        self.horizontalLayout_68.addWidget(self.botLPlotVgs)
        spacerItem17 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem17)
        self.botRPlotVgs = PlotWidget(self.tabVgs)
        self.botRPlotVgs.setObjectName("botRPlotVgs")
        self.horizontalLayout_68.addWidget(self.botRPlotVgs)
        spacerItem18 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem18)
        self.horizontalLayout_68.setStretch(1, 1)
        self.horizontalLayout_68.setStretch(3, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_68)
        self.verticalLayout_19.setStretch(0, 10)
        self.verticalLayout_19.setStretch(1, 10)
        self.gridLayout_11.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabVgs, "")
        self.tabGmId = QtWidgets.QWidget()
        self.tabGmId.setObjectName("tabGmId")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabGmId)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        spacerItem19 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem19)
        self.topLPlotGmId = PlotWidget(self.tabGmId)
        self.topLPlotGmId.setObjectName("topLPlotGmId")
        self.horizontalLayout_66.addWidget(self.topLPlotGmId)
        spacerItem20 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem20)
        self.topRPlotGmId = PlotWidget(self.tabGmId)
        self.topRPlotGmId.setObjectName("topRPlotGmId")
        self.horizontalLayout_66.addWidget(self.topRPlotGmId)
        spacerItem21 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem21)
        self.horizontalLayout_66.setStretch(1, 1)
        self.horizontalLayout_66.setStretch(3, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        spacerItem22 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem22)
        self.botLPlotGmId = PlotWidget(self.tabGmId)
        self.botLPlotGmId.setObjectName("botLPlotGmId")
        self.horizontalLayout_67.addWidget(self.botLPlotGmId)
        spacerItem23 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem23)
        self.botRPlotGmId = PlotWidget(self.tabGmId)
        self.botRPlotGmId.setObjectName("botRPlotGmId")
        self.horizontalLayout_67.addWidget(self.botRPlotGmId)
        spacerItem24 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem24)
        self.horizontalLayout_67.setStretch(1, 1)
        self.horizontalLayout_67.setStretch(3, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_67)
        self.verticalLayout_16.setStretch(0, 10)
        self.verticalLayout_16.setStretch(1, 10)
        self.gridLayout_4.addLayout(self.verticalLayout_16, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabGmId, "")
        self.tabGateL = QtWidgets.QWidget()
        self.tabGateL.setObjectName("tabGateL")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabGateL)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        spacerItem25 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem25)
        self.topLPlotL = PlotWidget(self.tabGateL)
        self.topLPlotL.setObjectName("topLPlotL")
        self.horizontalLayout_52.addWidget(self.topLPlotL)
        spacerItem26 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem26)
        self.topRPlotL = PlotWidget(self.tabGateL)
        self.topRPlotL.setObjectName("topRPlotL")
        self.horizontalLayout_52.addWidget(self.topRPlotL)
        spacerItem27 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem27)
        self.horizontalLayout_52.setStretch(1, 1)
        self.horizontalLayout_52.setStretch(3, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        spacerItem28 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem28)
        self.botLPlotL = PlotWidget(self.tabGateL)
        self.botLPlotL.setObjectName("botLPlotL")
        self.horizontalLayout_53.addWidget(self.botLPlotL)
        spacerItem29 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem29)
        self.botRPlotL = PlotWidget(self.tabGateL)
        self.botRPlotL.setObjectName("botRPlotL")
        self.horizontalLayout_53.addWidget(self.botRPlotL)
        spacerItem30 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem30)
        self.horizontalLayout_53.setStretch(1, 1)
        self.horizontalLayout_53.setStretch(3, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_53)
        self.verticalLayout_9.setStretch(0, 10)
        self.verticalLayout_9.setStretch(1, 10)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabGateL, "")
        self.tabOpt = QtWidgets.QWidget()
        self.tabOpt.setObjectName("tabOpt")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabOpt)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        spacerItem31 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem31)
        self.topLPlotOpt = PlotWidget(self.tabOpt)
        self.topLPlotOpt.setObjectName("topLPlotOpt")
        self.horizontalLayout_58.addWidget(self.topLPlotOpt)
        spacerItem32 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem32)
        self.topRPlotOpt = PlotWidget(self.tabOpt)
        self.topRPlotOpt.setObjectName("topRPlotOpt")
        self.horizontalLayout_58.addWidget(self.topRPlotOpt)
        spacerItem33 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem33)
        self.horizontalLayout_58.setStretch(1, 1)
        self.horizontalLayout_58.setStretch(3, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        spacerItem34 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem34)
        self.botLPlotOpt = PlotWidget(self.tabOpt)
        self.botLPlotOpt.setObjectName("botLPlotOpt")
        self.horizontalLayout_59.addWidget(self.botLPlotOpt)
        spacerItem35 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem35)
        self.botRPlotOpt = PlotWidget(self.tabOpt)
        self.botRPlotOpt.setObjectName("botRPlotOpt")
        self.horizontalLayout_59.addWidget(self.botRPlotOpt)
        spacerItem36 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem36)
        self.horizontalLayout_59.setStretch(1, 1)
        self.horizontalLayout_59.setStretch(3, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_59)
        self.verticalLayout_12.setStretch(0, 15)
        self.verticalLayout_12.setStretch(1, 15)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.tabWidgetPlots.addTab(self.tabOpt, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidgetPlots.addTab(self.tab, "")
        self.verticalLayoutPlot.addWidget(self.tabWidgetPlots)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.titleVstar = QtWidgets.QLabel(self.centralwidget)
        self.titleVstar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleVstar.setObjectName("titleVstar")
        self.horizontalLayout_71.addWidget(self.titleVstar)
        self.labelVstar = QtWidgets.QLabel(self.centralwidget)
        self.labelVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVstar.setObjectName("labelVstar")
        self.horizontalLayout_71.addWidget(self.labelVstar)
        self.horizontalLayout_71.setStretch(0, 3)
        self.horizontalLayout_71.setStretch(1, 4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.titleGmId = QtWidgets.QLabel(self.centralwidget)
        self.titleGmId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleGmId.setObjectName("titleGmId")
        self.horizontalLayout_70.addWidget(self.titleGmId)
        self.labelGmId = QtWidgets.QLabel(self.centralwidget)
        self.labelGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGmId.setObjectName("labelGmId")
        self.horizontalLayout_70.addWidget(self.labelGmId)
        self.horizontalLayout_70.setStretch(0, 3)
        self.horizontalLayout_70.setStretch(1, 4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.titleId = QtWidgets.QLabel(self.centralwidget)
        self.titleId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleId.setObjectName("titleId")
        self.horizontalLayout_69.addWidget(self.titleId)
        self.labelId = QtWidgets.QLabel(self.centralwidget)
        self.labelId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelId.setObjectName("labelId")
        self.horizontalLayout_69.addWidget(self.labelId)
        self.horizontalLayout_69.setStretch(0, 3)
        self.horizontalLayout_69.setStretch(1, 4)
        self.horizontalLayout_75.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.titleFt = QtWidgets.QLabel(self.centralwidget)
        self.titleFt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleFt.setObjectName("titleFt")
        self.horizontalLayout_72.addWidget(self.titleFt)
        self.labelFt = QtWidgets.QLabel(self.centralwidget)
        self.labelFt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFt.setObjectName("labelFt")
        self.horizontalLayout_72.addWidget(self.labelFt)
        self.horizontalLayout_72.setStretch(0, 3)
        self.horizontalLayout_72.setStretch(1, 4)
        self.horizontalLayout_75.addLayout(self.horizontalLayout_72)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.titleFOM = QtWidgets.QLabel(self.centralwidget)
        self.titleFOM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleFOM.setObjectName("titleFOM")
        self.horizontalLayout_73.addWidget(self.titleFOM)
        self.labelFOM = QtWidgets.QLabel(self.centralwidget)
        self.labelFOM.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFOM.setObjectName("labelFOM")
        self.horizontalLayout_73.addWidget(self.labelFOM)
        self.horizontalLayout_73.setStretch(0, 3)
        self.horizontalLayout_73.setStretch(1, 4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.titleGain = QtWidgets.QLabel(self.centralwidget)
        self.titleGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleGain.setObjectName("titleGain")
        self.horizontalLayout_74.addWidget(self.titleGain)
        self.labelGain = QtWidgets.QLabel(self.centralwidget)
        self.labelGain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGain.setObjectName("labelGain")
        self.horizontalLayout_74.addWidget(self.labelGain)
        self.horizontalLayout_74.setStretch(0, 3)
        self.horizontalLayout_74.setStretch(1, 4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.titleVgs = QtWidgets.QLabel(self.centralwidget)
        self.titleVgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleVgs.setObjectName("titleVgs")
        self.horizontalLayout_84.addWidget(self.titleVgs)
        self.labelVgs = QtWidgets.QLabel(self.centralwidget)
        self.labelVgs.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVgs.setObjectName("labelVgs")
        self.horizontalLayout_84.addWidget(self.labelVgs)
        self.horizontalLayout_84.setStretch(0, 3)
        self.horizontalLayout_84.setStretch(1, 4)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_84)
        self.horizontalLayout_89 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_89.setObjectName("horizontalLayout_89")
        self.titleVdsat = QtWidgets.QLabel(self.centralwidget)
        self.titleVdsat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleVdsat.setObjectName("titleVdsat")
        self.horizontalLayout_89.addWidget(self.titleVdsat)
        self.labelVdsat = QtWidgets.QLabel(self.centralwidget)
        self.labelVdsat.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVdsat.setObjectName("labelVdsat")
        self.horizontalLayout_89.addWidget(self.labelVdsat)
        self.horizontalLayout_89.setStretch(0, 3)
        self.horizontalLayout_89.setStretch(1, 4)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_89)
        self.horizontalLayout_33.setStretch(0, 1)
        self.horizontalLayout_33.setStretch(1, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_33)
        self.verticalLayoutPlot.setStretch(0, 1)
        self.verticalLayoutPlot.setStretch(1, 1)
        self.verticalLayoutPlot.setStretch(2, 20)
        self.verticalLayoutPlot.setStretch(3, 1)
        self.verticalLayoutPlot.setStretch(4, 1)
        self.verticalLayoutPlot.setStretch(5, 1)
        self.verticalLayoutPlot.setStretch(6, 1)
        self.horizontalLayoutMain.addLayout(self.verticalLayoutPlot)
        spacerItem37 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMain.addItem(spacerItem37)
        self.verticalLayoutFunc = QtWidgets.QVBoxLayout()
        self.verticalLayoutFunc.setObjectName("verticalLayoutFunc")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButtonMosDirSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMosDirSel.setObjectName("pushButtonMosDirSel")
        self.horizontalLayout_23.addWidget(self.pushButtonMosDirSel)
        self.pushButtonMosMatSet = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMosMatSet.sizePolicy().hasHeightForWidth())
        self.pushButtonMosMatSet.setSizePolicy(sizePolicy)
        self.pushButtonMosMatSet.setObjectName("pushButtonMosMatSet")
        self.horizontalLayout_23.addWidget(self.pushButtonMosMatSet)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.titleMosCharData = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleMosCharData.setFont(font)
        self.titleMosCharData.setAutoFillBackground(False)
        self.titleMosCharData.setStyleSheet("*{\n"
"background-color:rgb(240, 248, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.titleMosCharData.setText("")
        self.titleMosCharData.setAlignment(QtCore.Qt.AlignCenter)
        self.titleMosCharData.setObjectName("titleMosCharData")
        self.verticalLayout_2.addWidget(self.titleMosCharData)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFileList = QtWidgets.QLabel(self.centralwidget)
        self.labelFileList.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileList.setObjectName("labelFileList")
        self.verticalLayout.addWidget(self.labelFileList)
        self.listWidgetMat = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetMat.setStyleSheet("*{\n"
"background-color:rgb(240, 248, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.listWidgetMat.setObjectName("listWidgetMat")
        self.verticalLayout.addWidget(self.listWidgetMat)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 7)
        self.horizontalLayout_22.addLayout(self.verticalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButtonGateLSet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGateLSet.setObjectName("pushButtonGateLSet")
        self.horizontalLayout_34.addWidget(self.pushButtonGateLSet)
        self.pushButtonGateLRef = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGateLRef.setStyleSheet("")
        self.pushButtonGateLRef.setObjectName("pushButtonGateLRef")
        self.horizontalLayout_34.addWidget(self.pushButtonGateLRef)
        self.pushButtonGateLChk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGateLChk.setObjectName("pushButtonGateLChk")
        self.horizontalLayout_34.addWidget(self.pushButtonGateLChk)
        self.horizontalLayout_34.setStretch(0, 1)
        self.horizontalLayout_34.setStretch(1, 1)
        self.horizontalLayout_34.setStretch(2, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.labelGateL = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGateL.setFont(font)
        self.labelGateL.setStyleSheet("*{\n"
"background-color:rgb(153, 255, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.labelGateL.setText("")
        self.labelGateL.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGateL.setObjectName("labelGateL")
        self.horizontalLayout_37.addWidget(self.labelGateL)
        self.labelGateLRef = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGateLRef.setFont(font)
        self.labelGateLRef.setStyleSheet("*{\n"
"background-color:rgb(77,190,238);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.labelGateLRef.setText("")
        self.labelGateLRef.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGateLRef.setObjectName("labelGateLRef")
        self.horizontalLayout_37.addWidget(self.labelGateLRef)
        self.labelGateLChk = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelGateLChk.setFont(font)
        self.labelGateLChk.setStyleSheet("*{\n"
"background-color:rgb(102, 102, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.labelGateLChk.setText("")
        self.labelGateLChk.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGateLChk.setObjectName("labelGateLChk")
        self.horizontalLayout_37.addWidget(self.labelGateLChk)
        self.horizontalLayout_37.setStretch(0, 1)
        self.horizontalLayout_37.setStretch(1, 1)
        self.horizontalLayout_37.setStretch(2, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelLList = QtWidgets.QLabel(self.centralwidget)
        self.labelLList.setStyleSheet("")
        self.labelLList.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLList.setObjectName("labelLList")
        self.verticalLayout_13.addWidget(self.labelLList)
        self.listWidgetL = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetL.setObjectName("listWidgetL")
        self.verticalLayout_13.addWidget(self.listWidgetL)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelLListRef = QtWidgets.QLabel(self.centralwidget)
        self.labelLListRef.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLListRef.setObjectName("labelLListRef")
        self.verticalLayout_10.addWidget(self.labelLListRef)
        self.listWidgetLRef = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLRef.setStyleSheet("")
        self.listWidgetLRef.setObjectName("listWidgetLRef")
        self.verticalLayout_10.addWidget(self.listWidgetLRef)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.labelLListChk = QtWidgets.QLabel(self.centralwidget)
        self.labelLListChk.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLListChk.setObjectName("labelLListChk")
        self.verticalLayout_18.addWidget(self.labelLListChk)
        self.listWidgetLChk = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLChk.setStyleSheet("")
        self.listWidgetLChk.setObjectName("listWidgetLChk")
        self.verticalLayout_18.addWidget(self.listWidgetLChk)
        self.horizontalLayout.addLayout(self.verticalLayout_18)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 1)
        self.verticalLayout_14.setStretch(2, 7)
        self.horizontalLayout_22.addLayout(self.verticalLayout_14)
        self.horizontalLayout_22.setStretch(0, 2)
        self.horizontalLayout_22.setStretch(1, 3)
        self.verticalLayoutFunc.addLayout(self.horizontalLayout_22)
        self.groupBoxMosCheck = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxMosCheck.setObjectName("groupBoxMosCheck")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBoxMosCheck)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.titleBiasVds = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleBiasVds.setFont(font)
        self.titleBiasVds.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleBiasVds.setObjectName("titleBiasVds")
        self.horizontalLayout_36.addWidget(self.titleBiasVds)
        self.spinBoxBiasVds = QtWidgets.QSpinBox(self.groupBoxMosCheck)
        self.spinBoxBiasVds.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxBiasVds.setMaximum(1800)
        self.spinBoxBiasVds.setSingleStep(5)
        self.spinBoxBiasVds.setProperty("value", 900)
        self.spinBoxBiasVds.setObjectName("spinBoxBiasVds")
        self.horizontalLayout_36.addWidget(self.spinBoxBiasVds)
        self.horizontalLayout_36.setStretch(0, 1)
        self.horizontalLayout_36.setStretch(1, 1)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.titleBiasVbs = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleBiasVbs.setFont(font)
        self.titleBiasVbs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleBiasVbs.setObjectName("titleBiasVbs")
        self.horizontalLayout_35.addWidget(self.titleBiasVbs)
        self.spinBoxBiasVbs = QtWidgets.QSpinBox(self.groupBoxMosCheck)
        self.spinBoxBiasVbs.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxBiasVbs.setMaximum(1800)
        self.spinBoxBiasVbs.setSingleStep(25)
        self.spinBoxBiasVbs.setObjectName("spinBoxBiasVbs")
        self.horizontalLayout_35.addWidget(self.spinBoxBiasVbs)
        self.horizontalLayout_35.setStretch(0, 1)
        self.horizontalLayout_35.setStretch(1, 1)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_39.setStretch(0, 1)
        self.horizontalLayout_39.setStretch(1, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_39)
        self.tabWidgetMode = QtWidgets.QTabWidget(self.groupBoxMosCheck)
        self.tabWidgetMode.setObjectName("tabWidgetMode")
        self.tabSyn = QtWidgets.QWidget()
        self.tabSyn.setObjectName("tabSyn")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabSyn)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.checkBoxSynGmId = QtWidgets.QCheckBox(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSynGmId.setFont(font)
        self.checkBoxSynGmId.setObjectName("checkBoxSynGmId")
        self.horizontalLayout_27.addWidget(self.checkBoxSynGmId)
        self.lineEditSynGmId = QtWidgets.QLineEdit(self.tabSyn)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynGmId.setFont(font)
        self.lineEditSynGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynGmId.setObjectName("lineEditSynGmId")
        self.horizontalLayout_27.addWidget(self.lineEditSynGmId)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxSynVstar = QtWidgets.QCheckBox(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSynVstar.setFont(font)
        self.checkBoxSynVstar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxSynVstar.setObjectName("checkBoxSynVstar")
        self.horizontalLayout_5.addWidget(self.checkBoxSynVstar)
        self.lineEditSynVstar = QtWidgets.QLineEdit(self.tabSyn)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynVstar.setFont(font)
        self.lineEditSynVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynVstar.setObjectName("lineEditSynVstar")
        self.horizontalLayout_5.addWidget(self.lineEditSynVstar)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.checkBoxSynGm = QtWidgets.QCheckBox(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSynGm.setFont(font)
        self.checkBoxSynGm.setObjectName("checkBoxSynGm")
        self.horizontalLayout_26.addWidget(self.checkBoxSynGm)
        self.lineEditSynGm = QtWidgets.QLineEdit(self.tabSyn)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynGm.setFont(font)
        self.lineEditSynGm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynGm.setObjectName("lineEditSynGm")
        self.horizontalLayout_26.addWidget(self.lineEditSynGm)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBoxSynId = QtWidgets.QCheckBox(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSynId.setFont(font)
        self.checkBoxSynId.setObjectName("checkBoxSynId")
        self.horizontalLayout_12.addWidget(self.checkBoxSynId)
        self.lineEditSynId = QtWidgets.QLineEdit(self.tabSyn)
        self.lineEditSynId.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynId.setObjectName("lineEditSynId")
        self.horizontalLayout_12.addWidget(self.lineEditSynId)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.titleSynWidth = QtWidgets.QLabel(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynWidth.setFont(font)
        self.titleSynWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynWidth.setObjectName("titleSynWidth")
        self.horizontalLayout_10.addWidget(self.titleSynWidth)
        self.labelSynW = QtWidgets.QLabel(self.tabSyn)
        self.labelSynW.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynW.setObjectName("labelSynW")
        self.horizontalLayout_10.addWidget(self.labelSynW)
        self.horizontalLayout_78.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.titleSynVgs = QtWidgets.QLabel(self.tabSyn)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynVgs.setFont(font)
        self.titleSynVgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynVgs.setObjectName("titleSynVgs")
        self.horizontalLayout_76.addWidget(self.titleSynVgs)
        self.labelSynVgs = QtWidgets.QLabel(self.tabSyn)
        self.labelSynVgs.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynVgs.setObjectName("labelSynVgs")
        self.horizontalLayout_76.addWidget(self.labelSynVgs)
        self.horizontalLayout_76.setStretch(0, 1)
        self.horizontalLayout_76.setStretch(1, 1)
        self.horizontalLayout_78.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_78.setStretch(0, 1)
        self.horizontalLayout_78.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_78)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidgetMode.addTab(self.tabSyn, "")
        self.tabCal = QtWidgets.QWidget()
        self.tabCal.setObjectName("tabCal")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabCal)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.titleCalWidth = QtWidgets.QLabel(self.tabCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalWidth.setFont(font)
        self.titleCalWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalWidth.setObjectName("titleCalWidth")
        self.horizontalLayout_41.addWidget(self.titleCalWidth)
        self.lineEditCalWidth = QtWidgets.QLineEdit(self.tabCal)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCalWidth.setFont(font)
        self.lineEditCalWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCalWidth.setObjectName("lineEditCalWidth")
        self.horizontalLayout_41.addWidget(self.lineEditCalWidth)
        self.horizontalLayout_41.setStretch(0, 1)
        self.horizontalLayout_41.setStretch(1, 1)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.titleCalVgs = QtWidgets.QLabel(self.tabCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalVgs.setFont(font)
        self.titleCalVgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalVgs.setObjectName("titleCalVgs")
        self.horizontalLayout_40.addWidget(self.titleCalVgs)
        self.lineEditCalVgs = QtWidgets.QLineEdit(self.tabCal)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCalVgs.setFont(font)
        self.lineEditCalVgs.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCalVgs.setObjectName("lineEditCalVgs")
        self.horizontalLayout_40.addWidget(self.lineEditCalVgs)
        self.horizontalLayout_40.setStretch(0, 1)
        self.horizontalLayout_40.setStretch(1, 1)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_42.setStretch(0, 1)
        self.horizontalLayout_42.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem38)
        self.horizontalLayout_44.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.titleCalGmId = QtWidgets.QLabel(self.tabCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalGmId.setFont(font)
        self.titleCalGmId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalGmId.setObjectName("titleCalGmId")
        self.horizontalLayout_46.addWidget(self.titleCalGmId)
        self.labelCalGmId = QtWidgets.QLabel(self.tabCal)
        self.labelCalGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCalGmId.setObjectName("labelCalGmId")
        self.horizontalLayout_46.addWidget(self.labelCalGmId)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.titleCalVstar = QtWidgets.QLabel(self.tabCal)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalVstar.setFont(font)
        self.titleCalVstar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalVstar.setObjectName("titleCalVstar")
        self.horizontalLayout_47.addWidget(self.titleCalVstar)
        self.labelCalVstar = QtWidgets.QLabel(self.tabCal)
        self.labelCalVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCalVstar.setObjectName("labelCalVstar")
        self.horizontalLayout_47.addWidget(self.labelCalVstar)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_45.setStretch(0, 1)
        self.horizontalLayout_45.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_45)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidgetMode.addTab(self.tabCal, "")
        self.tabOptSetting = QtWidgets.QWidget()
        self.tabOptSetting.setObjectName("tabOptSetting")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabOptSetting)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.titleOppt = QtWidgets.QLabel(self.tabOptSetting)
        self.titleOppt.setStyleSheet("*{\n"
"color: rgb(0, 255, 0);\n"
"}")
        self.titleOppt.setAlignment(QtCore.Qt.AlignCenter)
        self.titleOppt.setObjectName("titleOppt")
        self.horizontalLayout_86.addWidget(self.titleOppt)
        self.titleSize = QtWidgets.QLabel(self.tabOptSetting)
        self.titleSize.setStyleSheet("*{\n"
"color: rgb(0, 128,255);\n"
"}")
        self.titleSize.setAlignment(QtCore.Qt.AlignCenter)
        self.titleSize.setObjectName("titleSize")
        self.horizontalLayout_86.addWidget(self.titleSize)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_86)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.checkBoxOptVstar = QtWidgets.QCheckBox(self.tabOptSetting)
        self.checkBoxOptVstar.setStyleSheet("*{\n"
"background-color:rgb(0,255,0);\n"
"}")
        self.checkBoxOptVstar.setObjectName("checkBoxOptVstar")
        self.horizontalLayout_61.addWidget(self.checkBoxOptVstar)
        self.labelOptVstar = QtWidgets.QLabel(self.tabOptSetting)
        self.labelOptVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOptVstar.setObjectName("labelOptVstar")
        self.horizontalLayout_61.addWidget(self.labelOptVstar)
        self.lineEditOptVstar = QtWidgets.QLineEdit(self.tabOptSetting)
        self.lineEditOptVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOptVstar.setObjectName("lineEditOptVstar")
        self.horizontalLayout_61.addWidget(self.lineEditOptVstar)
        self.horizontalLayout_61.setStretch(0, 4)
        self.horizontalLayout_61.setStretch(1, 1)
        self.horizontalLayout_61.setStretch(2, 3)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_38.setStretch(0, 1)
        self.horizontalLayout_38.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.checkBoxOptFt = QtWidgets.QCheckBox(self.tabOptSetting)
        self.checkBoxOptFt.setStyleSheet("*{\n"
"background-color:rgb(0,255,0);\n"
"}")
        self.checkBoxOptFt.setObjectName("checkBoxOptFt")
        self.horizontalLayout_63.addWidget(self.checkBoxOptFt)
        self.labelOptFt = QtWidgets.QLabel(self.tabOptSetting)
        self.labelOptFt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOptFt.setObjectName("labelOptFt")
        self.horizontalLayout_63.addWidget(self.labelOptFt)
        self.lineEditOptFt = QtWidgets.QLineEdit(self.tabOptSetting)
        self.lineEditOptFt.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOptFt.setObjectName("lineEditOptFt")
        self.horizontalLayout_63.addWidget(self.lineEditOptFt)
        self.horizontalLayout_63.setStretch(0, 4)
        self.horizontalLayout_63.setStretch(1, 1)
        self.horizontalLayout_63.setStretch(2, 3)
        self.horizontalLayout_87.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.checkBoxOptAvo = QtWidgets.QCheckBox(self.tabOptSetting)
        self.checkBoxOptAvo.setStyleSheet("*{\n"
"background-color:rgb(0,255,0);\n"
"}")
        self.checkBoxOptAvo.setObjectName("checkBoxOptAvo")
        self.horizontalLayout_62.addWidget(self.checkBoxOptAvo)
        self.labelOptAvo = QtWidgets.QLabel(self.tabOptSetting)
        self.labelOptAvo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOptAvo.setObjectName("labelOptAvo")
        self.horizontalLayout_62.addWidget(self.labelOptAvo)
        self.lineEditOptAvo = QtWidgets.QLineEdit(self.tabOptSetting)
        self.lineEditOptAvo.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOptAvo.setObjectName("lineEditOptAvo")
        self.horizontalLayout_62.addWidget(self.lineEditOptAvo)
        self.horizontalLayout_62.setStretch(0, 4)
        self.horizontalLayout_62.setStretch(1, 1)
        self.horizontalLayout_62.setStretch(2, 3)
        self.horizontalLayout_87.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_87.setStretch(0, 1)
        self.horizontalLayout_87.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_87)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.checkBoxOptGm = QtWidgets.QCheckBox(self.tabOptSetting)
        self.checkBoxOptGm.setStyleSheet("*{\n"
"background-color: rgb(0, 128,255);\n"
"}")
        self.checkBoxOptGm.setObjectName("checkBoxOptGm")
        self.horizontalLayout_83.addWidget(self.checkBoxOptGm)
        self.labelOptGm = QtWidgets.QLabel(self.tabOptSetting)
        self.labelOptGm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOptGm.setObjectName("labelOptGm")
        self.horizontalLayout_83.addWidget(self.labelOptGm)
        self.lineEditOptGm = QtWidgets.QLineEdit(self.tabOptSetting)
        self.lineEditOptGm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOptGm.setObjectName("lineEditOptGm")
        self.horizontalLayout_83.addWidget(self.lineEditOptGm)
        self.horizontalLayout_83.setStretch(0, 4)
        self.horizontalLayout_83.setStretch(1, 1)
        self.horizontalLayout_83.setStretch(2, 3)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_83)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.checkBoxOptArea = QtWidgets.QCheckBox(self.tabOptSetting)
        self.checkBoxOptArea.setStyleSheet("*{\n"
"background-color: rgb(0, 128,255);\n"
"}")
        self.checkBoxOptArea.setObjectName("checkBoxOptArea")
        self.horizontalLayout_81.addWidget(self.checkBoxOptArea)
        self.labelOptArea = QtWidgets.QLabel(self.tabOptSetting)
        self.labelOptArea.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOptArea.setObjectName("labelOptArea")
        self.horizontalLayout_81.addWidget(self.labelOptArea)
        self.lineEditOptArea = QtWidgets.QLineEdit(self.tabOptSetting)
        self.lineEditOptArea.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditOptArea.setObjectName("lineEditOptArea")
        self.horizontalLayout_81.addWidget(self.lineEditOptArea)
        self.horizontalLayout_81.setStretch(0, 4)
        self.horizontalLayout_81.setStretch(1, 1)
        self.horizontalLayout_81.setStretch(2, 3)
        self.horizontalLayout_64.addLayout(self.horizontalLayout_81)
        self.horizontalLayout_64.setStretch(0, 1)
        self.horizontalLayout_64.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_64)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(2, 1)
        self.gridLayout_9.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.tabWidgetMode.addTab(self.tabOptSetting, "")
        self.verticalLayout_17.addWidget(self.tabWidgetMode)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButtonSynMos = QtWidgets.QPushButton(self.groupBoxMosCheck)
        self.pushButtonSynMos.setStyleSheet("*{\n"
"color: rgb(51,51, 255);\n"
"}")
        self.pushButtonSynMos.setObjectName("pushButtonSynMos")
        self.horizontalLayout_28.addWidget(self.pushButtonSynMos)
        self.pushButtonCal = QtWidgets.QPushButton(self.groupBoxMosCheck)
        self.pushButtonCal.setStyleSheet("*{\n"
"color: rgb(51,51, 255);\n"
"}")
        self.pushButtonCal.setObjectName("pushButtonCal")
        self.horizontalLayout_28.addWidget(self.pushButtonCal)
        self.pushButtonFuEst = QtWidgets.QPushButton(self.groupBoxMosCheck)
        self.pushButtonFuEst.setObjectName("pushButtonFuEst")
        self.horizontalLayout_28.addWidget(self.pushButtonFuEst)
        self.pushButtonOptOp = QtWidgets.QPushButton(self.groupBoxMosCheck)
        self.pushButtonOptOp.setStyleSheet("*{\n"
"color: rgb(0, 255, 0);\n"
"}")
        self.pushButtonOptOp.setObjectName("pushButtonOptOp")
        self.horizontalLayout_28.addWidget(self.pushButtonOptOp)
        self.pushButtonOptSize = QtWidgets.QPushButton(self.groupBoxMosCheck)
        self.pushButtonOptSize.setStyleSheet("*{\n"
"color: rgb(0, 128,255);\n"
"}")
        self.pushButtonOptSize.setObjectName("pushButtonOptSize")
        self.horizontalLayout_28.addWidget(self.pushButtonOptSize)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 1)
        self.horizontalLayout_28.setStretch(2, 1)
        self.horizontalLayout_28.setStretch(3, 1)
        self.horizontalLayout_28.setStretch(4, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_28)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.titleSynCload = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynCload.setFont(font)
        self.titleSynCload.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynCload.setObjectName("titleSynCload")
        self.horizontalLayout_48.addWidget(self.titleSynCload)
        self.lineEditSynCload = QtWidgets.QLineEdit(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynCload.setFont(font)
        self.lineEditSynCload.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynCload.setObjectName("lineEditSynCload")
        self.horizontalLayout_48.addWidget(self.lineEditSynCload)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.titleChkVdsat = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkVdsat.setFont(font)
        self.titleChkVdsat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkVdsat.setObjectName("titleChkVdsat")
        self.horizontalLayout_77.addWidget(self.titleChkVdsat)
        self.labelChkVdsat = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkVdsat.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkVdsat.setObjectName("labelChkVdsat")
        self.horizontalLayout_77.addWidget(self.labelChkVdsat)
        self.horizontalLayout_77.setStretch(0, 1)
        self.horizontalLayout_77.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.titleChkGm = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkGm.setFont(font)
        self.titleChkGm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkGm.setObjectName("titleChkGm")
        self.horizontalLayout_82.addWidget(self.titleChkGm)
        self.labelChkGm = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkGm.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkGm.setObjectName("labelChkGm")
        self.horizontalLayout_82.addWidget(self.labelChkGm)
        self.horizontalLayout_80.addLayout(self.horizontalLayout_82)
        self.horizontalLayout_88 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_88.setObjectName("horizontalLayout_88")
        self.titleChkId = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkId.setFont(font)
        self.titleChkId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkId.setObjectName("titleChkId")
        self.horizontalLayout_88.addWidget(self.titleChkId)
        self.labelChkId = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkId.setObjectName("labelChkId")
        self.horizontalLayout_88.addWidget(self.labelChkId)
        self.horizontalLayout_80.addLayout(self.horizontalLayout_88)
        self.horizontalLayout_80.setStretch(0, 1)
        self.horizontalLayout_80.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.titleChkFt = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkFt.setFont(font)
        self.titleChkFt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkFt.setObjectName("titleChkFt")
        self.horizontalLayout_19.addWidget(self.titleChkFt)
        self.labelChkFt = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkFt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkFt.setObjectName("labelChkFt")
        self.horizontalLayout_19.addWidget(self.labelChkFt)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.titleChkCgg = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkCgg.setFont(font)
        self.titleChkCgg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkCgg.setObjectName("titleChkCgg")
        self.horizontalLayout_25.addWidget(self.titleChkCgg)
        self.labelChkCgg = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkCgg.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkCgg.setObjectName("labelChkCgg")
        self.horizontalLayout_25.addWidget(self.labelChkCgg)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.titleChkFug = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkFug.setFont(font)
        self.titleChkFug.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkFug.setObjectName("titleChkFug")
        self.horizontalLayout_20.addWidget(self.titleChkFug)
        self.labelChkFug = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkFug.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkFug.setObjectName("labelChkFug")
        self.horizontalLayout_20.addWidget(self.labelChkFug)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.titleChkVth = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkVth.setFont(font)
        self.titleChkVth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkVth.setObjectName("titleChkVth")
        self.horizontalLayout_29.addWidget(self.titleChkVth)
        self.labelChkVth = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkVth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkVth.setObjectName("labelChkVth")
        self.horizontalLayout_29.addWidget(self.labelChkVth)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_29)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.titleChkRout = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkRout.setFont(font)
        self.titleChkRout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkRout.setObjectName("titleChkRout")
        self.horizontalLayout_16.addWidget(self.titleChkRout)
        self.labelChkRout = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkRout.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkRout.setObjectName("labelChkRout")
        self.horizontalLayout_16.addWidget(self.labelChkRout)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.titleChkAv = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkAv.setFont(font)
        self.titleChkAv.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkAv.setObjectName("titleChkAv")
        self.horizontalLayout_17.addWidget(self.titleChkAv)
        self.labelChkAv = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkAv.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkAv.setObjectName("labelChkAv")
        self.horizontalLayout_17.addWidget(self.labelChkAv)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.titleChkIn = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkIn.setFont(font)
        self.titleChkIn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkIn.setObjectName("titleChkIn")
        self.horizontalLayout_31.addWidget(self.titleChkIn)
        self.labelChkIn = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkIn.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkIn.setObjectName("labelChkIn")
        self.horizontalLayout_31.addWidget(self.labelChkIn)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.titleChkVn = QtWidgets.QLabel(self.groupBoxMosCheck)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleChkVn.setFont(font)
        self.titleChkVn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleChkVn.setObjectName("titleChkVn")
        self.horizontalLayout_32.addWidget(self.titleChkVn)
        self.labelChkVn = QtWidgets.QLabel(self.groupBoxMosCheck)
        self.labelChkVn.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChkVn.setObjectName("labelChkVn")
        self.horizontalLayout_32.addWidget(self.labelChkVn)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_32)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.verticalLayout_5.setStretch(4, 1)
        self.verticalLayout_5.setStretch(5, 1)
        self.verticalLayout_17.addLayout(self.verticalLayout_5)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 6)
        self.verticalLayout_17.setStretch(2, 1)
        self.verticalLayout_17.setStretch(3, 7)
        self.gridLayout_10.addLayout(self.verticalLayout_17, 0, 0, 1, 1)
        self.verticalLayoutFunc.addWidget(self.groupBoxMosCheck)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.titleLog = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLog.setFont(font)
        self.titleLog.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleLog.setObjectName("titleLog")
        self.horizontalLayout_14.addWidget(self.titleLog)
        self.labelLog = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelLog.setFont(font)
        self.labelLog.setStyleSheet("*{\n"
"background-color:rgb(250, 250, 210);\n"
"border: 5 px solid rgb(0, 0, 0);\n"
"}")
        self.labelLog.setObjectName("labelLog")
        self.horizontalLayout_14.addWidget(self.labelLog)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 4)
        self.verticalLayoutFunc.addLayout(self.horizontalLayout_14)
        self.verticalLayoutFunc.setStretch(0, 16)
        self.verticalLayoutFunc.setStretch(1, 34)
        self.verticalLayoutFunc.setStretch(2, 2)
        self.horizontalLayoutMain.addLayout(self.verticalLayoutFunc)
        self.horizontalLayoutMain.setStretch(0, 220)
        self.horizontalLayoutMain.setStretch(1, 1)
        self.horizontalLayoutMain.setStretch(2, 160)
        self.verticalLayout_3.addLayout(self.horizontalLayoutMain)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 28)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        GmIdMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GmIdMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1162, 22))
        self.menubar.setObjectName("menubar")
        GmIdMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GmIdMainWindow)
        self.statusbar.setObjectName("statusbar")
        GmIdMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GmIdMainWindow)
        self.tabWidgetPlots.setCurrentIndex(0)
        self.tabWidgetMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GmIdMainWindow)

    def retranslateUi(self, GmIdMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GmIdMainWindow.setWindowTitle(_translate("GmIdMainWindow", "Gm Id GUI"))
        self.titleToolBox.setText(_translate("GmIdMainWindow", "Gm Id Sizing Box V0.2"))
        self.titlePlotCorner.setText(_translate("GmIdMainWindow", "Des Corner :"))
        self.comboBoxDesignCorner.setItemText(0, _translate("GmIdMainWindow", "TT"))
        self.comboBoxDesignCorner.setItemText(1, _translate("GmIdMainWindow", "FF"))
        self.comboBoxDesignCorner.setItemText(2, _translate("GmIdMainWindow", "SS"))
        self.comboBoxDesignCorner.setItemText(3, _translate("GmIdMainWindow", "FS"))
        self.comboBoxDesignCorner.setItemText(4, _translate("GmIdMainWindow", "SF"))
        self.pushButtonPlot.setText(_translate("GmIdMainWindow", "Plot"))
        self.checkBoxCornerTT.setText(_translate("GmIdMainWindow", "TT"))
        self.checkBoxCornerFF.setText(_translate("GmIdMainWindow", "FF"))
        self.checkBoxCornerSS.setText(_translate("GmIdMainWindow", "SS"))
        self.checkBoxCornerFS.setText(_translate("GmIdMainWindow", "FS"))
        self.checkBoxCornerSF.setText(_translate("GmIdMainWindow", "SF"))
        self.checkBoxRef.setText(_translate("GmIdMainWindow", "L - REF"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabVstar), _translate("GmIdMainWindow", "VStar"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabId), _translate("GmIdMainWindow", "Id"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabVgs), _translate("GmIdMainWindow", "Vgs"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabGmId), _translate("GmIdMainWindow", "GmId"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabGateL), _translate("GmIdMainWindow", "OptOp"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabOpt), _translate("GmIdMainWindow", "OptW"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tab), _translate("GmIdMainWindow", "Page"))
        self.titleVstar.setText(_translate("GmIdMainWindow", "V* :"))
        self.labelVstar.setText(_translate("GmIdMainWindow", "0.2"))
        self.titleGmId.setText(_translate("GmIdMainWindow", "Gm / Id :"))
        self.labelGmId.setText(_translate("GmIdMainWindow", "10"))
        self.titleId.setText(_translate("GmIdMainWindow", "Id* :"))
        self.labelId.setText(_translate("GmIdMainWindow", "10"))
        self.titleFt.setText(_translate("GmIdMainWindow", "ft :"))
        self.labelFt.setText(_translate("GmIdMainWindow", "100"))
        self.titleFOM.setText(_translate("GmIdMainWindow", "FOM :"))
        self.labelFOM.setText(_translate("GmIdMainWindow", "0.1"))
        self.titleGain.setText(_translate("GmIdMainWindow", "Avo :"))
        self.labelGain.setText(_translate("GmIdMainWindow", "50"))
        self.titleVgs.setText(_translate("GmIdMainWindow", "Vgs :"))
        self.labelVgs.setText(_translate("GmIdMainWindow", "0.75"))
        self.titleVdsat.setText(_translate("GmIdMainWindow", "Vdsat :"))
        self.labelVdsat.setText(_translate("GmIdMainWindow", "0.25"))
        self.pushButtonMosDirSel.setText(_translate("GmIdMainWindow", "Sel Dir"))
        self.pushButtonMosMatSet.setText(_translate("GmIdMainWindow", "Set Mat"))
        self.labelFileList.setText(_translate("GmIdMainWindow", "Mat File List"))
        self.pushButtonGateLSet.setText(_translate("GmIdMainWindow", "Ldes"))
        self.pushButtonGateLRef.setText(_translate("GmIdMainWindow", "Lref"))
        self.pushButtonGateLChk.setText(_translate("GmIdMainWindow", "Lchk"))
        self.labelLList.setText(_translate("GmIdMainWindow", "Design L"))
        self.labelLListRef.setText(_translate("GmIdMainWindow", "Ref. L"))
        self.labelLListChk.setText(_translate("GmIdMainWindow", "Chk. L"))
        self.groupBoxMosCheck.setTitle(_translate("GmIdMainWindow", "MOS Check"))
        self.titleBiasVds.setText(_translate("GmIdMainWindow", "Vds (mV):"))
        self.titleBiasVbs.setText(_translate("GmIdMainWindow", "Vbs (mV):"))
        self.checkBoxSynGmId.setText(_translate("GmIdMainWindow", "Gm/Id :"))
        self.lineEditSynGmId.setText(_translate("GmIdMainWindow", "10"))
        self.checkBoxSynVstar.setText(_translate("GmIdMainWindow", "V*(mV)"))
        self.lineEditSynVstar.setText(_translate("GmIdMainWindow", "200"))
        self.checkBoxSynGm.setText(_translate("GmIdMainWindow", "Gm(uS)"))
        self.lineEditSynGm.setText(_translate("GmIdMainWindow", "150"))
        self.checkBoxSynId.setText(_translate("GmIdMainWindow", "Id (uA)"))
        self.lineEditSynId.setText(_translate("GmIdMainWindow", "15"))
        self.titleSynWidth.setText(_translate("GmIdMainWindow", "W :"))
        self.labelSynW.setText(_translate("GmIdMainWindow", "10 um"))
        self.titleSynVgs.setText(_translate("GmIdMainWindow", "Vgs :"))
        self.labelSynVgs.setText(_translate("GmIdMainWindow", "900 mV"))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabSyn), _translate("GmIdMainWindow", "Syn"))
        self.titleCalWidth.setText(_translate("GmIdMainWindow", "W (um) :"))
        self.lineEditCalWidth.setText(_translate("GmIdMainWindow", "10"))
        self.titleCalVgs.setText(_translate("GmIdMainWindow", "Vgs (mV):"))
        self.lineEditCalVgs.setText(_translate("GmIdMainWindow", "0.9"))
        self.titleCalGmId.setText(_translate("GmIdMainWindow", "Gm/Id :"))
        self.labelCalGmId.setText(_translate("GmIdMainWindow", "10"))
        self.titleCalVstar.setText(_translate("GmIdMainWindow", "Vstar :"))
        self.labelCalVstar.setText(_translate("GmIdMainWindow", "0.2"))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabCal), _translate("GmIdMainWindow", "Cal"))
        self.titleOppt.setText(_translate("GmIdMainWindow", "Oppt"))
        self.titleSize.setText(_translate("GmIdMainWindow", "Size"))
        self.checkBoxOptVstar.setText(_translate("GmIdMainWindow", "V* (mV)"))
        self.labelOptVstar.setText(_translate("GmIdMainWindow", ">="))
        self.lineEditOptVstar.setText(_translate("GmIdMainWindow", "200"))
        self.checkBoxOptFt.setText(_translate("GmIdMainWindow", "Ft (MHz)"))
        self.labelOptFt.setText(_translate("GmIdMainWindow", ">="))
        self.lineEditOptFt.setText(_translate("GmIdMainWindow", "100"))
        self.checkBoxOptAvo.setText(_translate("GmIdMainWindow", "Av"))
        self.labelOptAvo.setText(_translate("GmIdMainWindow", ">="))
        self.lineEditOptAvo.setText(_translate("GmIdMainWindow", "50"))
        self.checkBoxOptGm.setText(_translate("GmIdMainWindow", "Gm (uS)"))
        self.labelOptGm.setText(_translate("GmIdMainWindow", "="))
        self.lineEditOptGm.setText(_translate("GmIdMainWindow", "20"))
        self.checkBoxOptArea.setText(_translate("GmIdMainWindow", "Area"))
        self.labelOptArea.setText(_translate("GmIdMainWindow", "="))
        self.lineEditOptArea.setText(_translate("GmIdMainWindow", "20"))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabOptSetting), _translate("GmIdMainWindow", "Opt"))
        self.pushButtonSynMos.setText(_translate("GmIdMainWindow", "Syn"))
        self.pushButtonCal.setText(_translate("GmIdMainWindow", "Cal"))
        self.pushButtonFuEst.setText(_translate("GmIdMainWindow", "Est"))
        self.pushButtonOptOp.setText(_translate("GmIdMainWindow", "Oppt"))
        self.pushButtonOptSize.setText(_translate("GmIdMainWindow", "Size"))
        self.titleSynCload.setText(_translate("GmIdMainWindow", "Cload(fF):"))
        self.lineEditSynCload.setText(_translate("GmIdMainWindow", "50"))
        self.titleChkVdsat.setText(_translate("GmIdMainWindow", "Vdsat :"))
        self.labelChkVdsat.setText(_translate("GmIdMainWindow", "900 mV"))
        self.titleChkGm.setText(_translate("GmIdMainWindow", "Gm :"))
        self.labelChkGm.setText(_translate("GmIdMainWindow", "10"))
        self.titleChkId.setText(_translate("GmIdMainWindow", "Id :"))
        self.labelChkId.setText(_translate("GmIdMainWindow", "10"))
        self.titleChkFt.setText(_translate("GmIdMainWindow", "ft :"))
        self.labelChkFt.setText(_translate("GmIdMainWindow", "100k"))
        self.titleChkCgg.setText(_translate("GmIdMainWindow", "Cgg :"))
        self.labelChkCgg.setText(_translate("GmIdMainWindow", "0.3"))
        self.titleChkFug.setText(_translate("GmIdMainWindow", "fug :"))
        self.labelChkFug.setText(_translate("GmIdMainWindow", "10"))
        self.titleChkVth.setText(_translate("GmIdMainWindow", "Vth :"))
        self.labelChkVth.setText(_translate("GmIdMainWindow", "0.5"))
        self.titleChkRout.setText(_translate("GmIdMainWindow", "Rout :"))
        self.labelChkRout.setText(_translate("GmIdMainWindow", "100k"))
        self.titleChkAv.setText(_translate("GmIdMainWindow", "Avo :"))
        self.labelChkAv.setText(_translate("GmIdMainWindow", "10"))
        self.titleChkIn.setText(_translate("GmIdMainWindow", "In :"))
        self.labelChkIn.setText(_translate("GmIdMainWindow", "0.3"))
        self.titleChkVn.setText(_translate("GmIdMainWindow", "Vn :"))
        self.labelChkVn.setText(_translate("GmIdMainWindow", "10"))
        self.titleLog.setText(_translate("GmIdMainWindow", "Log:"))
        self.labelLog.setText(_translate("GmIdMainWindow", "Warning"))

from pyqtgraph import PlotWidget
