# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gmIdSizingGuiBasic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GmIdMainWindow(object):
    def setupUi(self, GmIdMainWindow):
        GmIdMainWindow.setObjectName("GmIdMainWindow")
        GmIdMainWindow.resize(972, 876)
        self.centralwidget = QtWidgets.QWidget(GmIdMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleToolBox = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleToolBox.setFont(font)
        self.titleToolBox.setAlignment(QtCore.Qt.AlignCenter)
        self.titleToolBox.setObjectName("titleToolBox")
        self.verticalLayout_3.addWidget(self.titleToolBox)
        self.horizontalLayoutMain = QtWidgets.QHBoxLayout()
        self.horizontalLayoutMain.setObjectName("horizontalLayoutMain")
        self.verticalLayoutPlot = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlot.setObjectName("verticalLayoutPlot")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.titlePlotCorner = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titlePlotCorner.setFont(font)
        self.titlePlotCorner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titlePlotCorner.setObjectName("titlePlotCorner")
        self.horizontalLayout_21.addWidget(self.titlePlotCorner)
        self.comboBoxDesignCorner = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDesignCorner.sizePolicy().hasHeightForWidth())
        self.comboBoxDesignCorner.setSizePolicy(sizePolicy)
        self.comboBoxDesignCorner.setObjectName("comboBoxDesignCorner")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.comboBoxDesignCorner.addItem("")
        self.horizontalLayout_21.addWidget(self.comboBoxDesignCorner)
        self.checkBoxCornerTT = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerTT.setStyleSheet("*{\n"
"background-color:rgb(119, 172, 48);\n"
"}")
        self.checkBoxCornerTT.setObjectName("checkBoxCornerTT")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerTT)
        self.checkBoxCornerFF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerFF.setStyleSheet("*{\n"
"background-color:rgb(0, 114, 189);\n"
"}")
        self.checkBoxCornerFF.setObjectName("checkBoxCornerFF")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerFF)
        self.checkBoxCornerSS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerSS.setStyleSheet("*{\n"
"background-color:rgb(126, 47, 142);\n"
"}")
        self.checkBoxCornerSS.setObjectName("checkBoxCornerSS")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerSS)
        self.checkBoxCornerFS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerFS.setStyleSheet("*{\n"
"background-color:rgb(217, 83, 25);\n"
"}")
        self.checkBoxCornerFS.setObjectName("checkBoxCornerFS")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerFS)
        self.checkBoxCornerSF = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxCornerSF.setStyleSheet("*{\n"
"background-color:rgb(237,177,32);\n"
"}")
        self.checkBoxCornerSF.setObjectName("checkBoxCornerSF")
        self.horizontalLayout_21.addWidget(self.checkBoxCornerSF)
        self.checkBoxRef = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRef.setStyleSheet("*{\n"
"background-color:rgb(77,190,238);\n"
"}")
        self.checkBoxRef.setObjectName("checkBoxRef")
        self.horizontalLayout_21.addWidget(self.checkBoxRef)
        self.pushButtonPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.horizontalLayout_21.addWidget(self.pushButtonPlot)
        self.horizontalLayout_21.setStretch(0, 2)
        self.horizontalLayout_21.setStretch(1, 1)
        self.horizontalLayout_21.setStretch(2, 2)
        self.horizontalLayout_21.setStretch(3, 2)
        self.horizontalLayout_21.setStretch(4, 2)
        self.horizontalLayout_21.setStretch(5, 2)
        self.horizontalLayout_21.setStretch(6, 2)
        self.horizontalLayout_21.setStretch(7, 2)
        self.horizontalLayout_21.setStretch(8, 2)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_21)
        self.tabWidgetPlots = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetPlots.setObjectName("tabWidgetPlots")
        self.tabVstar = QtWidgets.QWidget()
        self.tabVstar.setObjectName("tabVstar")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tabVstar)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 481, 601))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem)
        self.topPlotVstar = PlotWidget(self.layoutWidget_2)
        self.topPlotVstar.setObjectName("topPlotVstar")
        self.horizontalLayout_49.addWidget(self.topPlotVstar)
        spacerItem1 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem1)
        self.horizontalLayout_49.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        spacerItem2 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem2)
        self.midPlotVstar = PlotWidget(self.layoutWidget_2)
        self.midPlotVstar.setObjectName("midPlotVstar")
        self.horizontalLayout_50.addWidget(self.midPlotVstar)
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem3)
        self.horizontalLayout_50.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem4)
        self.botPlotVstar = PlotWidget(self.layoutWidget_2)
        self.botPlotVstar.setObjectName("botPlotVstar")
        self.horizontalLayout_51.addWidget(self.botPlotVstar)
        spacerItem5 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_51.addItem(spacerItem5)
        self.horizontalLayout_51.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_51)
        self.verticalLayout_8.setStretch(0, 10)
        self.verticalLayout_8.setStretch(1, 10)
        self.verticalLayout_8.setStretch(2, 10)
        self.tabWidgetPlots.addTab(self.tabVstar, "")
        self.tabTest = QtWidgets.QWidget()
        self.tabTest.setObjectName("tabTest")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tabTest)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 481, 601))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        spacerItem6 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem6)
        self.topPlotId = PlotWidget(self.layoutWidget_4)
        self.topPlotId.setObjectName("topPlotId")
        self.horizontalLayout_55.addWidget(self.topPlotId)
        spacerItem7 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_55.addItem(spacerItem7)
        self.horizontalLayout_55.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem8 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem8)
        self.midPlotId = PlotWidget(self.layoutWidget_4)
        self.midPlotId.setObjectName("midPlotId")
        self.horizontalLayout_57.addWidget(self.midPlotId)
        spacerItem9 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem9)
        self.horizontalLayout_57.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        spacerItem10 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem10)
        self.botPlotId = PlotWidget(self.layoutWidget_4)
        self.botPlotId.setObjectName("botPlotId")
        self.horizontalLayout_56.addWidget(self.botPlotId)
        spacerItem11 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_56.addItem(spacerItem11)
        self.horizontalLayout_56.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_56)
        self.verticalLayout_11.setStretch(0, 10)
        self.verticalLayout_11.setStretch(1, 10)
        self.verticalLayout_11.setStretch(2, 10)
        self.tabWidgetPlots.addTab(self.tabTest, "")
        self.tabGmId = QtWidgets.QWidget()
        self.tabGmId.setObjectName("tabGmId")
        self.layoutWidget = QtWidgets.QWidget(self.tabGmId)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.topPlotGmId = PlotWidget(self.layoutWidget)
        self.topPlotGmId.setObjectName("topPlotGmId")
        self.verticalLayout_7.addWidget(self.topPlotGmId)
        self.midPlotGmId = PlotWidget(self.layoutWidget)
        self.midPlotGmId.setObjectName("midPlotGmId")
        self.verticalLayout_7.addWidget(self.midPlotGmId)
        self.botPlotGmId = PlotWidget(self.layoutWidget)
        self.botPlotGmId.setObjectName("botPlotGmId")
        self.verticalLayout_7.addWidget(self.botPlotGmId)
        self.verticalLayout_7.setStretch(0, 10)
        self.verticalLayout_7.setStretch(1, 10)
        self.verticalLayout_7.setStretch(2, 10)
        self.tabWidgetPlots.addTab(self.tabGmId, "")
        self.tabGateL = QtWidgets.QWidget()
        self.tabGateL.setObjectName("tabGateL")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tabGateL)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 481, 601))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        spacerItem12 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem12)
        self.topLPlotL = PlotWidget(self.layoutWidget_3)
        self.topLPlotL.setObjectName("topLPlotL")
        self.horizontalLayout_52.addWidget(self.topLPlotL)
        spacerItem13 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem13)
        self.horizontalLayout_52.setStretch(1, 2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        spacerItem14 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem14)
        self.midLPlotL = PlotWidget(self.layoutWidget_3)
        self.midLPlotL.setObjectName("midLPlotL")
        self.horizontalLayout_54.addWidget(self.midLPlotL)
        spacerItem15 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem15)
        self.horizontalLayout_54.setStretch(1, 10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        spacerItem16 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem16)
        self.botLPlotL = PlotWidget(self.layoutWidget_3)
        self.botLPlotL.setObjectName("botLPlotL")
        self.horizontalLayout_53.addWidget(self.botLPlotL)
        spacerItem17 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_53.addItem(spacerItem17)
        self.horizontalLayout_53.setStretch(1, 10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_53)
        self.verticalLayout_9.setStretch(0, 10)
        self.verticalLayout_9.setStretch(1, 10)
        self.verticalLayout_9.setStretch(2, 10)
        self.tabWidgetPlots.addTab(self.tabGateL, "")
        self.tabOpt = QtWidgets.QWidget()
        self.tabOpt.setObjectName("tabOpt")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tabOpt)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 481, 601))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        spacerItem18 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem18)
        self.topPlotOpt = PlotWidget(self.layoutWidget_5)
        self.topPlotOpt.setObjectName("topPlotOpt")
        self.horizontalLayout_58.addWidget(self.topPlotOpt)
        spacerItem19 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem19)
        self.horizontalLayout_58.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        spacerItem20 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem20)
        self.midPlotOpt = PlotWidget(self.layoutWidget_5)
        self.midPlotOpt.setObjectName("midPlotOpt")
        self.horizontalLayout_59.addWidget(self.midPlotOpt)
        spacerItem21 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem21)
        self.horizontalLayout_59.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        spacerItem22 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem22)
        self.botPlotOpt = PlotWidget(self.layoutWidget_5)
        self.botPlotOpt.setObjectName("botPlotOpt")
        self.horizontalLayout_60.addWidget(self.botPlotOpt)
        spacerItem23 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem23)
        self.horizontalLayout_60.setStretch(1, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.pushButtonOpt = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButtonOpt.setObjectName("pushButtonOpt")
        self.horizontalLayout_64.addWidget(self.pushButtonOpt)
        self.checkBoxOptId = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBoxOptId.setObjectName("checkBoxOptId")
        self.horizontalLayout_64.addWidget(self.checkBoxOptId)
        self.checkBoxOptVstar = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBoxOptVstar.setObjectName("checkBoxOptVstar")
        self.horizontalLayout_64.addWidget(self.checkBoxOptVstar)
        self.checkBoxOptAvo = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBoxOptAvo.setObjectName("checkBoxOptAvo")
        self.horizontalLayout_64.addWidget(self.checkBoxOptAvo)
        self.checkBoxOptFt = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkBoxOptFt.setObjectName("checkBoxOptFt")
        self.horizontalLayout_64.addWidget(self.checkBoxOptFt)
        self.horizontalLayout_64.setStretch(0, 1)
        self.horizontalLayout_64.setStretch(1, 2)
        self.horizontalLayout_64.setStretch(2, 2)
        self.horizontalLayout_64.setStretch(3, 2)
        self.horizontalLayout_64.setStretch(4, 2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_64)
        self.verticalLayout_12.setStretch(0, 15)
        self.verticalLayout_12.setStretch(1, 15)
        self.verticalLayout_12.setStretch(2, 15)
        self.verticalLayout_12.setStretch(3, 1)
        self.tabWidgetPlots.addTab(self.tabOpt, "")
        self.verticalLayoutPlot.addWidget(self.tabWidgetPlots)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleId = QtWidgets.QLabel(self.centralwidget)
        self.titleId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleId.setObjectName("titleId")
        self.horizontalLayout_3.addWidget(self.titleId)
        self.labelId = QtWidgets.QLabel(self.centralwidget)
        self.labelId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelId.setObjectName("labelId")
        self.horizontalLayout_3.addWidget(self.labelId)
        self.titleGmId = QtWidgets.QLabel(self.centralwidget)
        self.titleGmId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleGmId.setObjectName("titleGmId")
        self.horizontalLayout_3.addWidget(self.titleGmId)
        self.labelGmId = QtWidgets.QLabel(self.centralwidget)
        self.labelGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGmId.setObjectName("labelGmId")
        self.horizontalLayout_3.addWidget(self.labelGmId)
        self.titleVstar = QtWidgets.QLabel(self.centralwidget)
        self.titleVstar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleVstar.setObjectName("titleVstar")
        self.horizontalLayout_3.addWidget(self.titleVstar)
        self.labelVstar = QtWidgets.QLabel(self.centralwidget)
        self.labelVstar.setObjectName("labelVstar")
        self.horizontalLayout_3.addWidget(self.labelVstar)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titleFt = QtWidgets.QLabel(self.centralwidget)
        self.titleFt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleFt.setObjectName("titleFt")
        self.horizontalLayout_4.addWidget(self.titleFt)
        self.labelFt = QtWidgets.QLabel(self.centralwidget)
        self.labelFt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFt.setObjectName("labelFt")
        self.horizontalLayout_4.addWidget(self.labelFt)
        self.titleFOM = QtWidgets.QLabel(self.centralwidget)
        self.titleFOM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleFOM.setObjectName("titleFOM")
        self.horizontalLayout_4.addWidget(self.titleFOM)
        self.labelFOM = QtWidgets.QLabel(self.centralwidget)
        self.labelFOM.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFOM.setObjectName("labelFOM")
        self.horizontalLayout_4.addWidget(self.labelFOM)
        self.titleGain = QtWidgets.QLabel(self.centralwidget)
        self.titleGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleGain.setObjectName("titleGain")
        self.horizontalLayout_4.addWidget(self.titleGain)
        self.labelGain = QtWidgets.QLabel(self.centralwidget)
        self.labelGain.setObjectName("labelGain")
        self.horizontalLayout_4.addWidget(self.labelGain)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.horizontalLayout_4.setStretch(5, 1)
        self.verticalLayoutPlot.addLayout(self.horizontalLayout_4)
        self.verticalLayoutPlot.setStretch(0, 1)
        self.verticalLayoutPlot.setStretch(1, 32)
        self.horizontalLayoutMain.addLayout(self.verticalLayoutPlot)
        spacerItem24 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutMain.addItem(spacerItem24)
        self.verticalLayoutFunc = QtWidgets.QVBoxLayout()
        self.verticalLayoutFunc.setObjectName("verticalLayoutFunc")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButtonMosDirSel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMosDirSel.setObjectName("pushButtonMosDirSel")
        self.horizontalLayout_23.addWidget(self.pushButtonMosDirSel)
        self.pushButtonMosMatSet = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMosMatSet.sizePolicy().hasHeightForWidth())
        self.pushButtonMosMatSet.setSizePolicy(sizePolicy)
        self.pushButtonMosMatSet.setObjectName("pushButtonMosMatSet")
        self.horizontalLayout_23.addWidget(self.pushButtonMosMatSet)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.titleMosCharData = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleMosCharData.setFont(font)
        self.titleMosCharData.setAutoFillBackground(False)
        self.titleMosCharData.setStyleSheet("*{\n"
"background-color:rgb(240, 248, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.titleMosCharData.setText("")
        self.titleMosCharData.setAlignment(QtCore.Qt.AlignCenter)
        self.titleMosCharData.setObjectName("titleMosCharData")
        self.verticalLayout_2.addWidget(self.titleMosCharData)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFileList = QtWidgets.QLabel(self.centralwidget)
        self.labelFileList.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileList.setObjectName("labelFileList")
        self.verticalLayout.addWidget(self.labelFileList)
        self.listWidgetMat = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetMat.setStyleSheet("*{\n"
"background-color:rgb(240, 248, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.listWidgetMat.setObjectName("listWidgetMat")
        self.verticalLayout.addWidget(self.listWidgetMat)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 8)
        self.horizontalLayout_22.addLayout(self.verticalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButtonGateLSet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGateLSet.setObjectName("pushButtonGateLSet")
        self.horizontalLayout_34.addWidget(self.pushButtonGateLSet)
        self.pushButtonGateLRef = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGateLRef.setStyleSheet("")
        self.pushButtonGateLRef.setObjectName("pushButtonGateLRef")
        self.horizontalLayout_34.addWidget(self.pushButtonGateLRef)
        self.verticalLayout_14.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.labelGateL = QtWidgets.QLabel(self.centralwidget)
        self.labelGateL.setStyleSheet("*{\n"
"background-color:rgb(255, 255, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.labelGateL.setText("")
        self.labelGateL.setObjectName("labelGateL")
        self.horizontalLayout_37.addWidget(self.labelGateL)
        self.labelGateLRef = QtWidgets.QLabel(self.centralwidget)
        self.labelGateLRef.setStyleSheet("*{\n"
"background-color:rgb(255, 255, 255);\n"
"border: 15 px solid rgb(0, 0, 0);\n"
"}")
        self.labelGateLRef.setText("")
        self.labelGateLRef.setObjectName("labelGateLRef")
        self.horizontalLayout_37.addWidget(self.labelGateLRef)
        self.horizontalLayout_37.setStretch(0, 1)
        self.horizontalLayout_37.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_37)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelLList = QtWidgets.QLabel(self.centralwidget)
        self.labelLList.setStyleSheet("")
        self.labelLList.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLList.setObjectName("labelLList")
        self.verticalLayout_13.addWidget(self.labelLList)
        self.listWidgetL = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetL.setObjectName("listWidgetL")
        self.verticalLayout_13.addWidget(self.listWidgetL)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelLListRef = QtWidgets.QLabel(self.centralwidget)
        self.labelLListRef.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLListRef.setObjectName("labelLListRef")
        self.verticalLayout_10.addWidget(self.labelLListRef)
        self.listWidgetLRef = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLRef.setStyleSheet("")
        self.listWidgetLRef.setObjectName("listWidgetLRef")
        self.verticalLayout_10.addWidget(self.listWidgetLRef)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_14.addLayout(self.horizontalLayout)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 1)
        self.verticalLayout_14.setStretch(2, 8)
        self.horizontalLayout_22.addLayout(self.verticalLayout_14)
        self.horizontalLayout_22.setStretch(0, 3)
        self.horizontalLayout_22.setStretch(1, 2)
        self.verticalLayoutFunc.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.titleBiasVds = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleBiasVds.setFont(font)
        self.titleBiasVds.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleBiasVds.setObjectName("titleBiasVds")
        self.horizontalLayout_36.addWidget(self.titleBiasVds)
        self.spinBoxBiasVds = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxBiasVds.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxBiasVds.setMaximum(1800)
        self.spinBoxBiasVds.setSingleStep(5)
        self.spinBoxBiasVds.setProperty("value", 900)
        self.spinBoxBiasVds.setObjectName("spinBoxBiasVds")
        self.horizontalLayout_36.addWidget(self.spinBoxBiasVds)
        self.horizontalLayout_36.setStretch(0, 1)
        self.horizontalLayout_36.setStretch(1, 1)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.titleBiasVbs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleBiasVbs.setFont(font)
        self.titleBiasVbs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleBiasVbs.setObjectName("titleBiasVbs")
        self.horizontalLayout_35.addWidget(self.titleBiasVbs)
        self.spinBoxBiasVbs = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxBiasVbs.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxBiasVbs.setMaximum(1800)
        self.spinBoxBiasVbs.setSingleStep(25)
        self.spinBoxBiasVbs.setObjectName("spinBoxBiasVbs")
        self.horizontalLayout_35.addWidget(self.spinBoxBiasVbs)
        self.horizontalLayout_35.setStretch(0, 1)
        self.horizontalLayout_35.setStretch(1, 1)
        self.horizontalLayout_39.addLayout(self.horizontalLayout_35)
        self.verticalLayoutFunc.addLayout(self.horizontalLayout_39)
        self.tabWidgetMode = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMode.setObjectName("tabWidgetMode")
        self.tabSyn = QtWidgets.QWidget()
        self.tabSyn.setObjectName("tabSyn")
        self.layoutWidget1 = QtWidgets.QWidget(self.tabSyn)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.titleSynGm = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynGm.setFont(font)
        self.titleSynGm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynGm.setObjectName("titleSynGm")
        self.horizontalLayout_26.addWidget(self.titleSynGm)
        self.lineEditSynGm = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynGm.setFont(font)
        self.lineEditSynGm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynGm.setObjectName("lineEditSynGm")
        self.horizontalLayout_26.addWidget(self.lineEditSynGm)
        self.horizontalLayout_26.setStretch(0, 1)
        self.horizontalLayout_26.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonSynGmId = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonSynGmId.setObjectName("pushButtonSynGmId")
        self.horizontalLayout_6.addWidget(self.pushButtonSynGmId)
        self.pushButtonSynVstar = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonSynVstar.setObjectName("pushButtonSynVstar")
        self.horizontalLayout_6.addWidget(self.pushButtonSynVstar)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.titleSynGmId = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynGmId.setFont(font)
        self.titleSynGmId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynGmId.setObjectName("titleSynGmId")
        self.horizontalLayout_27.addWidget(self.titleSynGmId)
        self.lineEditSynGmId = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynGmId.setFont(font)
        self.lineEditSynGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynGmId.setObjectName("lineEditSynGmId")
        self.horizontalLayout_27.addWidget(self.lineEditSynGmId)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.titleSynVstar = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynVstar.setFont(font)
        self.titleSynVstar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynVstar.setObjectName("titleSynVstar")
        self.horizontalLayout_5.addWidget(self.titleSynVstar)
        self.lineEditSynVstar = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynVstar.setFont(font)
        self.lineEditSynVstar.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynVstar.setObjectName("lineEditSynVstar")
        self.horizontalLayout_5.addWidget(self.lineEditSynVstar)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.titleSynWidth = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynWidth.setFont(font)
        self.titleSynWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynWidth.setObjectName("titleSynWidth")
        self.horizontalLayout_10.addWidget(self.titleSynWidth)
        self.labelSynW = QtWidgets.QLabel(self.layoutWidget1)
        self.labelSynW.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynW.setObjectName("labelSynW")
        self.horizontalLayout_10.addWidget(self.labelSynW)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.titleSynId = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynId.setFont(font)
        self.titleSynId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynId.setObjectName("titleSynId")
        self.horizontalLayout_9.addWidget(self.titleSynId)
        self.labelSynId = QtWidgets.QLabel(self.layoutWidget1)
        self.labelSynId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynId.setObjectName("labelSynId")
        self.horizontalLayout_9.addWidget(self.labelSynId)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.tabWidgetMode.addTab(self.tabSyn, "")
        self.tabCal = QtWidgets.QWidget()
        self.tabCal.setObjectName("tabCal")
        self.layoutWidget2 = QtWidgets.QWidget(self.tabCal)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 371, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.titleCalWidth = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalWidth.setFont(font)
        self.titleCalWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalWidth.setObjectName("titleCalWidth")
        self.horizontalLayout_41.addWidget(self.titleCalWidth)
        self.lineEditCalWidth = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCalWidth.setFont(font)
        self.lineEditCalWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCalWidth.setObjectName("lineEditCalWidth")
        self.horizontalLayout_41.addWidget(self.lineEditCalWidth)
        self.horizontalLayout_41.setStretch(0, 1)
        self.horizontalLayout_41.setStretch(1, 1)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.titleCalVgs = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalVgs.setFont(font)
        self.titleCalVgs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalVgs.setObjectName("titleCalVgs")
        self.horizontalLayout_40.addWidget(self.titleCalVgs)
        self.lineEditCalVgs = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditCalVgs.setFont(font)
        self.lineEditCalVgs.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCalVgs.setObjectName("lineEditCalVgs")
        self.horizontalLayout_40.addWidget(self.lineEditCalVgs)
        self.horizontalLayout_40.setStretch(0, 1)
        self.horizontalLayout_40.setStretch(1, 1)
        self.horizontalLayout_42.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_42.setStretch(0, 1)
        self.horizontalLayout_42.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem25)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem26)
        self.pushButtonCal = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButtonCal.setObjectName("pushButtonCal")
        self.horizontalLayout_43.addWidget(self.pushButtonCal)
        self.horizontalLayout_43.setStretch(0, 1)
        self.horizontalLayout_43.setStretch(1, 1)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44.setStretch(0, 1)
        self.horizontalLayout_44.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.titleCalGmId = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalGmId.setFont(font)
        self.titleCalGmId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalGmId.setObjectName("titleCalGmId")
        self.horizontalLayout_46.addWidget(self.titleCalGmId)
        self.labelCalGmId = QtWidgets.QLabel(self.layoutWidget2)
        self.labelCalGmId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCalGmId.setObjectName("labelCalGmId")
        self.horizontalLayout_46.addWidget(self.labelCalGmId)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.titleCalId = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleCalId.setFont(font)
        self.titleCalId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCalId.setObjectName("titleCalId")
        self.horizontalLayout_47.addWidget(self.titleCalId)
        self.labelCalId = QtWidgets.QLabel(self.layoutWidget2)
        self.labelCalId.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCalId.setObjectName("labelCalId")
        self.horizontalLayout_47.addWidget(self.labelCalId)
        self.horizontalLayout_45.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_45.setStretch(0, 1)
        self.horizontalLayout_45.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_45)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.tabWidgetMode.addTab(self.tabCal, "")
        self.tabOptSetting = QtWidgets.QWidget()
        self.tabOptSetting.setObjectName("tabOptSetting")
        self.widget = QtWidgets.QWidget(self.tabOptSetting)
        self.widget.setGeometry(QtCore.QRect(10, 10, 378, 71))
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.titleOptVstar = QtWidgets.QLabel(self.widget)
        self.titleOptVstar.setObjectName("titleOptVstar")
        self.horizontalLayout_61.addWidget(self.titleOptVstar)
        self.labelOptVstar = QtWidgets.QLabel(self.widget)
        self.labelOptVstar.setObjectName("labelOptVstar")
        self.horizontalLayout_61.addWidget(self.labelOptVstar)
        self.lineEditOptVstar = QtWidgets.QLineEdit(self.widget)
        self.lineEditOptVstar.setObjectName("lineEditOptVstar")
        self.horizontalLayout_61.addWidget(self.lineEditOptVstar)
        self.horizontalLayout_61.setStretch(0, 2)
        self.horizontalLayout_61.setStretch(1, 1)
        self.horizontalLayout_61.setStretch(2, 2)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.titleOptId = QtWidgets.QLabel(self.widget)
        self.titleOptId.setObjectName("titleOptId")
        self.horizontalLayout_65.addWidget(self.titleOptId)
        self.labelOptId = QtWidgets.QLabel(self.widget)
        self.labelOptId.setObjectName("labelOptId")
        self.horizontalLayout_65.addWidget(self.labelOptId)
        self.lineEditOptId = QtWidgets.QLineEdit(self.widget)
        self.lineEditOptId.setObjectName("lineEditOptId")
        self.horizontalLayout_65.addWidget(self.lineEditOptId)
        self.horizontalLayout_65.setStretch(0, 2)
        self.horizontalLayout_65.setStretch(1, 1)
        self.horizontalLayout_65.setStretch(2, 2)
        self.horizontalLayout_38.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_38.setStretch(0, 1)
        self.horizontalLayout_38.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.titleOptFt = QtWidgets.QLabel(self.widget)
        self.titleOptFt.setObjectName("titleOptFt")
        self.horizontalLayout_63.addWidget(self.titleOptFt)
        self.labelOptFt = QtWidgets.QLabel(self.widget)
        self.labelOptFt.setObjectName("labelOptFt")
        self.horizontalLayout_63.addWidget(self.labelOptFt)
        self.lineEditFt = QtWidgets.QLineEdit(self.widget)
        self.lineEditFt.setObjectName("lineEditFt")
        self.horizontalLayout_63.addWidget(self.lineEditFt)
        self.horizontalLayout_63.setStretch(0, 2)
        self.horizontalLayout_63.setStretch(1, 1)
        self.horizontalLayout_63.setStretch(2, 2)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.titleOptAvo = QtWidgets.QLabel(self.widget)
        self.titleOptAvo.setObjectName("titleOptAvo")
        self.horizontalLayout_62.addWidget(self.titleOptAvo)
        self.labelOptAvo = QtWidgets.QLabel(self.widget)
        self.labelOptAvo.setObjectName("labelOptAvo")
        self.horizontalLayout_62.addWidget(self.labelOptAvo)
        self.lineEditAvo = QtWidgets.QLineEdit(self.widget)
        self.lineEditAvo.setObjectName("lineEditAvo")
        self.horizontalLayout_62.addWidget(self.lineEditAvo)
        self.horizontalLayout_62.setStretch(0, 2)
        self.horizontalLayout_62.setStretch(1, 1)
        self.horizontalLayout_62.setStretch(2, 2)
        self.horizontalLayout_48.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_48.setStretch(0, 1)
        self.horizontalLayout_48.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_48)
        self.tabWidgetMode.addTab(self.tabOptSetting, "")
        self.verticalLayoutFunc.addWidget(self.tabWidgetMode)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.titleSynCload = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynCload.setFont(font)
        self.titleSynCload.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynCload.setObjectName("titleSynCload")
        self.horizontalLayout_28.addWidget(self.titleSynCload)
        self.lineEditSynCload = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditSynCload.setFont(font)
        self.lineEditSynCload.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditSynCload.setObjectName("lineEditSynCload")
        self.horizontalLayout_28.addWidget(self.lineEditSynCload)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem27)
        self.pushButtonFuEst = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFuEst.setObjectName("pushButtonFuEst")
        self.horizontalLayout_12.addWidget(self.pushButtonFuEst)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.titleSynFt = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynFt.setFont(font)
        self.titleSynFt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynFt.setObjectName("titleSynFt")
        self.horizontalLayout_19.addWidget(self.titleSynFt)
        self.labelSynFt = QtWidgets.QLabel(self.centralwidget)
        self.labelSynFt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynFt.setObjectName("labelSynFt")
        self.horizontalLayout_19.addWidget(self.labelSynFt)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.titleSynFu = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynFu.setFont(font)
        self.titleSynFu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynFu.setObjectName("titleSynFu")
        self.horizontalLayout_20.addWidget(self.titleSynFu)
        self.labelSynFu = QtWidgets.QLabel(self.centralwidget)
        self.labelSynFu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynFu.setObjectName("labelSynFu")
        self.horizontalLayout_20.addWidget(self.labelSynFu)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.titleSynVsat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynVsat.setFont(font)
        self.titleSynVsat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynVsat.setObjectName("titleSynVsat")
        self.horizontalLayout_25.addWidget(self.titleSynVsat)
        self.labelSynVsat = QtWidgets.QLabel(self.centralwidget)
        self.labelSynVsat.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynVsat.setObjectName("labelSynVsat")
        self.horizontalLayout_25.addWidget(self.labelSynVsat)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.titleSynVth = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynVth.setFont(font)
        self.titleSynVth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynVth.setObjectName("titleSynVth")
        self.horizontalLayout_29.addWidget(self.titleSynVth)
        self.labelSynVth = QtWidgets.QLabel(self.centralwidget)
        self.labelSynVth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynVth.setObjectName("labelSynVth")
        self.horizontalLayout_29.addWidget(self.labelSynVth)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_29)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.titleSynRout = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynRout.setFont(font)
        self.titleSynRout.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynRout.setObjectName("titleSynRout")
        self.horizontalLayout_16.addWidget(self.titleSynRout)
        self.labelSynRout = QtWidgets.QLabel(self.centralwidget)
        self.labelSynRout.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynRout.setObjectName("labelSynRout")
        self.horizontalLayout_16.addWidget(self.labelSynRout)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.titleSynAv0 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynAv0.setFont(font)
        self.titleSynAv0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynAv0.setObjectName("titleSynAv0")
        self.horizontalLayout_17.addWidget(self.titleSynAv0)
        self.labelSynAv0 = QtWidgets.QLabel(self.centralwidget)
        self.labelSynAv0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynAv0.setObjectName("labelSynAv0")
        self.horizontalLayout_17.addWidget(self.labelSynAv0)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_17)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.titleSynIn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynIn.setFont(font)
        self.titleSynIn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynIn.setObjectName("titleSynIn")
        self.horizontalLayout_31.addWidget(self.titleSynIn)
        self.labelSynIn = QtWidgets.QLabel(self.centralwidget)
        self.labelSynIn.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynIn.setObjectName("labelSynIn")
        self.horizontalLayout_31.addWidget(self.labelSynIn)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.titleSynVn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleSynVn.setFont(font)
        self.titleSynVn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleSynVn.setObjectName("titleSynVn")
        self.horizontalLayout_32.addWidget(self.titleSynVn)
        self.labelSynVn = QtWidgets.QLabel(self.centralwidget)
        self.labelSynVn.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSynVn.setObjectName("labelSynVn")
        self.horizontalLayout_32.addWidget(self.labelSynVn)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_32)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.comboBoxExtCheck = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxExtCheck.setObjectName("comboBoxExtCheck")
        self.horizontalLayout_33.addWidget(self.comboBoxExtCheck)
        self.labelExtCheck = QtWidgets.QLabel(self.centralwidget)
        self.labelExtCheck.setStyleSheet("*{\n"
"background-color:rgb(255, 255, 255);\n"
"border: 5 px solid rgb(0, 0, 0);\n"
"}")
        self.labelExtCheck.setText("")
        self.labelExtCheck.setObjectName("labelExtCheck")
        self.horizontalLayout_33.addWidget(self.labelExtCheck)
        self.pushButtonExtCheck = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExtCheck.setObjectName("pushButtonExtCheck")
        self.horizontalLayout_33.addWidget(self.pushButtonExtCheck)
        self.horizontalLayout_33.setStretch(0, 1)
        self.horizontalLayout_33.setStretch(1, 1)
        self.horizontalLayout_33.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_33)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.verticalLayout_5.setStretch(4, 1)
        self.verticalLayout_5.setStretch(5, 1)
        self.verticalLayoutFunc.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.titleLog = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLog.setFont(font)
        self.titleLog.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleLog.setObjectName("titleLog")
        self.horizontalLayout_14.addWidget(self.titleLog)
        self.labelLog = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelLog.setFont(font)
        self.labelLog.setStyleSheet("*{\n"
"background-color:rgb(250, 250, 210);\n"
"border: 5 px solid rgb(0, 0, 0);\n"
"}")
        self.labelLog.setObjectName("labelLog")
        self.horizontalLayout_14.addWidget(self.labelLog)
        self.horizontalLayout_14.setStretch(0, 1)
        self.horizontalLayout_14.setStretch(1, 4)
        self.verticalLayoutFunc.addLayout(self.horizontalLayout_14)
        self.verticalLayoutFunc.setStretch(0, 14)
        self.verticalLayoutFunc.setStretch(1, 2)
        self.verticalLayoutFunc.setStretch(2, 8)
        self.verticalLayoutFunc.setStretch(3, 12)
        self.verticalLayoutFunc.setStretch(4, 2)
        self.horizontalLayoutMain.addLayout(self.verticalLayoutFunc)
        self.horizontalLayoutMain.setStretch(0, 100)
        self.horizontalLayoutMain.setStretch(1, 1)
        self.horizontalLayoutMain.setStretch(2, 80)
        self.verticalLayout_3.addLayout(self.horizontalLayoutMain)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 20)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        GmIdMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GmIdMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 22))
        self.menubar.setObjectName("menubar")
        GmIdMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GmIdMainWindow)
        self.statusbar.setObjectName("statusbar")
        GmIdMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GmIdMainWindow)
        self.tabWidgetPlots.setCurrentIndex(4)
        self.tabWidgetMode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GmIdMainWindow)

    def retranslateUi(self, GmIdMainWindow):
        _translate = QtCore.QCoreApplication.translate
        GmIdMainWindow.setWindowTitle(_translate("GmIdMainWindow", "MainWindow"))
        self.titleToolBox.setText(_translate("GmIdMainWindow", "Gm Id Sizing Box V0.1"))
        self.titlePlotCorner.setText(_translate("GmIdMainWindow", "Corner:"))
        self.comboBoxDesignCorner.setItemText(0, _translate("GmIdMainWindow", "TT"))
        self.comboBoxDesignCorner.setItemText(1, _translate("GmIdMainWindow", "FF"))
        self.comboBoxDesignCorner.setItemText(2, _translate("GmIdMainWindow", "SS"))
        self.comboBoxDesignCorner.setItemText(3, _translate("GmIdMainWindow", "FS"))
        self.comboBoxDesignCorner.setItemText(4, _translate("GmIdMainWindow", "SF"))
        self.checkBoxCornerTT.setText(_translate("GmIdMainWindow", "TT"))
        self.checkBoxCornerFF.setText(_translate("GmIdMainWindow", "FF"))
        self.checkBoxCornerSS.setText(_translate("GmIdMainWindow", "SS"))
        self.checkBoxCornerFS.setText(_translate("GmIdMainWindow", "FS"))
        self.checkBoxCornerSF.setText(_translate("GmIdMainWindow", "SF"))
        self.checkBoxRef.setText(_translate("GmIdMainWindow", "REF"))
        self.pushButtonPlot.setText(_translate("GmIdMainWindow", "Plot"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabVstar), _translate("GmIdMainWindow", "VStar"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabTest), _translate("GmIdMainWindow", "Id"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabGmId), _translate("GmIdMainWindow", "GmId"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabGateL), _translate("GmIdMainWindow", "GateL"))
        self.pushButtonOpt.setText(_translate("GmIdMainWindow", "Opt"))
        self.checkBoxOptId.setText(_translate("GmIdMainWindow", "Id"))
        self.checkBoxOptVstar.setText(_translate("GmIdMainWindow", "Vstar"))
        self.checkBoxOptAvo.setText(_translate("GmIdMainWindow", "Avo"))
        self.checkBoxOptFt.setText(_translate("GmIdMainWindow", "Ft"))
        self.tabWidgetPlots.setTabText(self.tabWidgetPlots.indexOf(self.tabOpt), _translate("GmIdMainWindow", "Opt"))
        self.titleId.setText(_translate("GmIdMainWindow", "Id* :"))
        self.labelId.setText(_translate("GmIdMainWindow", "10"))
        self.titleGmId.setText(_translate("GmIdMainWindow", "Gm/Id :"))
        self.labelGmId.setText(_translate("GmIdMainWindow", "0.1"))
        self.titleVstar.setText(_translate("GmIdMainWindow", "V* :"))
        self.labelVstar.setText(_translate("GmIdMainWindow", "0.2"))
        self.titleFt.setText(_translate("GmIdMainWindow", "ft :"))
        self.labelFt.setText(_translate("GmIdMainWindow", "100"))
        self.titleFOM.setText(_translate("GmIdMainWindow", "ft*gm/Id :"))
        self.labelFOM.setText(_translate("GmIdMainWindow", "0.1"))
        self.titleGain.setText(_translate("GmIdMainWindow", "Gain :"))
        self.labelGain.setText(_translate("GmIdMainWindow", "0.2"))
        self.pushButtonMosDirSel.setText(_translate("GmIdMainWindow", "Sel"))
        self.pushButtonMosMatSet.setText(_translate("GmIdMainWindow", "Set"))
        self.labelFileList.setText(_translate("GmIdMainWindow", "Mat File List"))
        self.pushButtonGateLSet.setText(_translate("GmIdMainWindow", "L"))
        self.pushButtonGateLRef.setText(_translate("GmIdMainWindow", "Lref"))
        self.labelLList.setText(_translate("GmIdMainWindow", "Design L"))
        self.labelLListRef.setText(_translate("GmIdMainWindow", "Ref. L"))
        self.titleBiasVds.setText(_translate("GmIdMainWindow", "Vds :"))
        self.titleBiasVbs.setText(_translate("GmIdMainWindow", "Vbs :"))
        self.titleSynGm.setText(_translate("GmIdMainWindow", "Gm(ms):"))
        self.lineEditSynGm.setText(_translate("GmIdMainWindow", "1.5"))
        self.pushButtonSynGmId.setText(_translate("GmIdMainWindow", "gmId"))
        self.pushButtonSynVstar.setText(_translate("GmIdMainWindow", "V*"))
        self.titleSynGmId.setText(_translate("GmIdMainWindow", "Gm/Id(S/A):"))
        self.lineEditSynGmId.setText(_translate("GmIdMainWindow", "10"))
        self.titleSynVstar.setText(_translate("GmIdMainWindow", "V*(V):"))
        self.lineEditSynVstar.setText(_translate("GmIdMainWindow", "0.2"))
        self.titleSynWidth.setText(_translate("GmIdMainWindow", "W:"))
        self.labelSynW.setText(_translate("GmIdMainWindow", "10"))
        self.titleSynId.setText(_translate("GmIdMainWindow", "Id:"))
        self.labelSynId.setText(_translate("GmIdMainWindow", "10"))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabSyn), _translate("GmIdMainWindow", "Syn"))
        self.titleCalWidth.setText(_translate("GmIdMainWindow", "W:"))
        self.lineEditCalWidth.setText(_translate("GmIdMainWindow", "10"))
        self.titleCalVgs.setText(_translate("GmIdMainWindow", "Vgs:"))
        self.lineEditCalVgs.setText(_translate("GmIdMainWindow", "0.9"))
        self.pushButtonCal.setText(_translate("GmIdMainWindow", "Check"))
        self.titleCalGmId.setText(_translate("GmIdMainWindow", "Gm/Id:"))
        self.labelCalGmId.setText(_translate("GmIdMainWindow", "10"))
        self.titleCalId.setText(_translate("GmIdMainWindow", "Id:"))
        self.labelCalId.setText(_translate("GmIdMainWindow", "10"))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabCal), _translate("GmIdMainWindow", "Cal"))
        self.titleOptVstar.setText(_translate("GmIdMainWindow", "Vstar"))
        self.labelOptVstar.setText(_translate("GmIdMainWindow", ">="))
        self.titleOptId.setText(_translate("GmIdMainWindow", "Id"))
        self.labelOptId.setText(_translate("GmIdMainWindow", "<="))
        self.titleOptFt.setText(_translate("GmIdMainWindow", "Ft"))
        self.labelOptFt.setText(_translate("GmIdMainWindow", ">="))
        self.titleOptAvo.setText(_translate("GmIdMainWindow", "Avo"))
        self.labelOptAvo.setText(_translate("GmIdMainWindow", ">="))
        self.tabWidgetMode.setTabText(self.tabWidgetMode.indexOf(self.tabOptSetting), _translate("GmIdMainWindow", "Opt"))
        self.titleSynCload.setText(_translate("GmIdMainWindow", "Cload(fF):"))
        self.lineEditSynCload.setText(_translate("GmIdMainWindow", "50"))
        self.pushButtonFuEst.setText(_translate("GmIdMainWindow", "Est"))
        self.titleSynFt.setText(_translate("GmIdMainWindow", "ft:"))
        self.labelSynFt.setText(_translate("GmIdMainWindow", "100k"))
        self.titleSynFu.setText(_translate("GmIdMainWindow", "fu:"))
        self.labelSynFu.setText(_translate("GmIdMainWindow", "10"))
        self.titleSynVsat.setText(_translate("GmIdMainWindow", "Vsat:"))
        self.labelSynVsat.setText(_translate("GmIdMainWindow", "0.3"))
        self.titleSynVth.setText(_translate("GmIdMainWindow", "Vt:"))
        self.labelSynVth.setText(_translate("GmIdMainWindow", "0.5"))
        self.titleSynRout.setText(_translate("GmIdMainWindow", "Rout:"))
        self.labelSynRout.setText(_translate("GmIdMainWindow", "100k"))
        self.titleSynAv0.setText(_translate("GmIdMainWindow", "Av0:"))
        self.labelSynAv0.setText(_translate("GmIdMainWindow", "10"))
        self.titleSynIn.setText(_translate("GmIdMainWindow", "In:"))
        self.labelSynIn.setText(_translate("GmIdMainWindow", "0.3"))
        self.titleSynVn.setText(_translate("GmIdMainWindow", "Vn:"))
        self.labelSynVn.setText(_translate("GmIdMainWindow", "10"))
        self.pushButtonExtCheck.setText(_translate("GmIdMainWindow", "Check"))
        self.titleLog.setText(_translate("GmIdMainWindow", "Log:"))
        self.labelLog.setText(_translate("GmIdMainWindow", "Warning"))

from pyqtgraph import PlotWidget
